### ISSUE TITLE
Boost Signals Deprecated on Ubuntu 14.04

### ISSUE THREAD

**Issue by chadrockey** [ros/geometry#60] opened 2014-03-30 08:22 UTC
While compiling imu_pipeline, I get a very long warning about boost signals being deprecated via tf/tf.h.

[ 26%] In file included from /usr/include/boost/signals.hpp:9:0,
                 from /opt/ros/indigo/include/tf/tf.h:45,
                 from /home/chadrockey/ws/src/imu_pipeline/src/imu_transformer.cpp:35:
/usr/include/boost/signal.hpp:17:4: warning: #warning "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-Wcpp]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."

**Comment by dirk-thomas** [comment] 2014-03-30 16:25
Duplicate of #23.

**Closed as completed by dirk-thomas** 2014-03-30 16:25 UTC
Labels: duplicate
