### ISSUE TITLE
TransformBroadcaster() does not receive consecutive transformations

### ISSUE THREAD

**Issue by JoonasMelin** [ros/geometry#75] opened 2014-12-02 14:33 UTC
I am using the default TF version that comes with Indigo.
The code to reproduce this error:

``` python
#!/usr/bin/env python
import rospy
import tf


if __name__ == '__main__':
    rospy.init_node('tftest', log_level=rospy.INFO)

    br = tf.TransformBroadcaster()
    tr = tf.TransformListener()


    rospy.loginfo("Spinning..")
    rospy.sleep(0.2) #This delay seems to be also needed
    while not rospy.is_shutdown():
        curTime = rospy.Time.now()
        #rospy.sleep(0.1)
        br.sendTransform((0,0,0), (0,0,0, 1), curTime, 'frame1', 'frame2')
        #rospy.sleep(0.02) #This delay is needed to retain both transformations
        br.sendTransform((0,0,0), (0,0,0, 1), curTime, 'dummy0', 'dummy')
        tr.waitForTransform('frame1', 'frame2', curTime, rospy.Duration(2))
        print("Got transform")
        rospy.sleep(0.2)

```

This error occurs if two transformations are sent too close to each others (delay of 0.02 s seems to be enough for my case) It would seem that some buffer is filling up too fast etc. Quick look through the TF code looked like there is a buffer of 100 values so that should not be an issue.

I was getting similar errors to #73 originally, so these might be related.

**Comment by tfoote** [comment] 2014-12-07 08:13
This looks like a duplicate of #71

**Closed as completed by tfoote** 2014-12-07 08:13 UTC
