### ISSUE TITLE
Name Clashes

### ISSUE THREAD

**Issue by zoumaguanxin** [ros/geometry#196] opened 2019-10-23 07:32 UTC
Hi,
   In related [wiki](http://wiki.ros.org/tf#tf_echo), the usage of `tf_echo` is the following:
```
 tf_echo <source_frame> <target_frame>
 
```
  It is very strange that the result of `tf_echo` is not consistent with the tf `static_transform_publisher` published. It confused me long time until I found some notes in this code.  In this [code](https://github.com/ros/geometry/blob/00a32d024af476bf50822e6df2fe2ec97765b1a9/tf/src/tf_echo.cpp#L122), the `source_frameid` is passed to `target_frame` argument of lookuptransform function.  When  `source frame` and `target frame` are used to distinct frames, it means that source frame is a moving frame, target frame is fixed. the transform from source frame to target frame is equal to the transform that can transform the point in source frame into target frame. I think `tf_echo` should keep same convention about frame name with `lookuptransform` function. This convention is also conformed by robotics.

**Comment by tfoote** [comment] 2019-10-28 23:13
Duplicate of #111 #108

**Closed as completed by tfoote** 2019-10-28 23:13 UTC
